### ISSUE TITLE
limitation of timed metadata track in dash client model (value, id)

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#10]
The timed metadata track in this document has some limitations: 

1. multiple timed metadata samples at the same time are not allowed, as by isobmff
2. id and value is missing compared to mpd and inband Events, 
   especially without *id* we cannot detect duplicates for the timed metadata, without *value* the subscheme cannot be identified. The description of the processing model does not account 
   for this absence in the text, leaving processing of timed metadata ill defined.
3. different tracks are needed for each metadata type, as URIMetaSampleEntry is used to signal the type of metadata. In practice it is not good to use many different tracks.

A practical solution, could be to carry DASHeventMessageBox structure in the sample. 

This way: 

1. multiple DASHeventMessageBox box can be embedded in a single sample, allowing multiple events at the same time without problem with isobmff
2. id and value can be signalled in the DASHeventMessageBox, allowing subscheme and duplicate detection
3. scheme_id_uri can be different for different samples, allowing carriage of different metadata types in one track. 
4. This would make the timed metadata track more consistent with inband event messages 'emsg' and mpd events

**Comment by irajs** [comment]
I agree with the concept and benefits. However, this addition needs to happen in CMAF and/or in DASH-IF IOP as the content format.

**Comment by haudiobe** [comment]
(Event TF 2019/06/14) We need input

**Comment by RufaelDev** [comment]
example of a timed metadata track, 
![Timed-MetaData-2018-v3](https://user-images.githubusercontent.com/10517746/59696822-080f2e00-91ed-11e9-80c7-f1ecf9647764.png)

**Comment by RufaelDev** [comment]
Some additional summary of the drawbacks of timed metadata in the current event processing model

1. id,value to identify the sample, these are not specified in regular timed metadata track, needed to detect duplicate samples     
2. multiple events at the same time (this cannot be signalled as having 0 duration and same presentation time is not allowed)
3. an event occuring before the previous event was finished (overlapping events)
4. vlaue/id are then also missing in the API to the client
5. it is not possible to have metadata of different schemes in one track

These can be solved by embedding DashEventMessageBox structure in the timed metadata sample
The URIMetaSampleEntry in track refers to dash events and the samples containing the one or more DashEventMessageBox signal the scheme of data embedded in the DashEventMessageBox 

the encapsulation offers the following advantages:

1. The schemeIdUri can signal the scheme of the specific event in the DASHEventMessageBox in the multiple types of timed metadata in a track can exist
2. id,value can be re-used by the client processing model and API, duplicate events can be detected,
3. multiple events at the same time in timed metadata tracks: embed multiple EventMessageBox in a single sample 
4. a sample occuring before the previous sample was finished: the duration of the metadatasample is shortened but the DASHEventMessageBox can still signal the correct duration
6. the DASHEventMessageBox will enable consistent API to client compared to inband and mpd events 
7. convergence DASH event and timed metadata sample 
8. by having the time timeline and keeping separate metadata track, the advantages of metadata track are kept, like lightweight, not interleaved with media, late binding etc.

Alternative ways to handle are like for example fragmented webvtt, but the one presented here seems 
to offer the most consistent model for handling timed metadata with inband/mpd DashEvents

This approach is deployed today by commercial encoder vendors aswell for using timed metadata.

**Comment by unifiedstreaming** [comment]
We added the proposed text in pull request: https://github.com/Dash-Industry-Forum/Events/pull/38

**Comment by irajs** [comment]
I added Rufael's edits (editorials) as well as a section on embedded timed metadata track, (copy/paste from Rufael's pull request, in my branch because we have two parallel branches and needed to merge the documents. The embedded timed metadata track has its own section + a note that this is under review. The merged version can be found at: https://github.com/irajs/Events/blob/master/01-Events.inc.md

**Comment by irajs** [comment]
(Event TF 6/28) We added the revised text in the pull request. We add a note in the top of section:

"(Editor's note) This clause is recently added. During the Community Review period, Reviewers are welcomed to comment on the technical content and alignment of the text with MPEG specifications and provide comments wrt if any additional text is needed e.g. signaling of embedded event schemes ids in init segment or MPD."
