### ISSUE TITLE
include @contentEncoding

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#12]
@contentEncoding was a feature added in amendment 5, it allows the string to represent base64 encoded string. Consider passing this argument to the client aswell on dispatch, the client can then do the base64 decoding as the decoded message may not be of string type. 

1. explain @contentEncoding in the client model MPD Event
2. dispatch the @contentEncoding to the client

**Comment by irajs** [comment]
Added @contentEncoding in table.
Added a function and a short text to define the base64 decoding requirement for dash client receiving the messageData.

 @contentEncoding is not dispatched to the application (if that is meant) as the base64 decoding must be done in the DASH client.
