### ISSUE TITLE
[EventAPI]how to signal unknown duration

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#15]
How to signal unknown duration in the eventAPI ? 
could one use the value 0xFFFFFFFF ? One could use zero duration ?

**Comment by irajs** [comment]
Form 23009-1:
1) For emsg: "event_duration provides the duration of event in media presentation time. In version 0-, the timescale is indicated in the timescale field; in version 1, the timescale of the MovieHeaderBox is used. The value 0xFFFF indicates an unknown duration."

2) For Event@duration: "specifies the presentation duration of the event.
The value of the duration in seconds is the division of the value of this attribute and the value of the @timescale attribute.
If not present, the value of the duration is unknown."

0 is valid as a duration value. Therefore it seems we need to use xFFFFFFFF for unknown duration.

**Comment by irajs** [comment]
[F2F meeting] we take out @timescale in EventAPI.  The parameters duration and presentationtime is passed in msec,

**Comment by irajs** [comment]
Both are implemented: removal of timescale and maximum value for duration when duration is unknown.
