### ISSUE TITLE
Allow application to subscribe to all events with a single request

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Events#18]
The application may wish to subscribe to all events with a single call, versus 6 individual subscriptions. To allow this, two changes need to be made:
1. The subscription call should have a reserved value for scheme_id_uri/value (such as NULL or * or "") which indicates that all events should be forwarded.
2. The DASH client, when  invoking the function specified in the callbackFunction argument should echo back the scheme_id_uri and value properties of each event for both On-receive and On-start modes. Clients subscribing to a specific scheme_id_uri can simply ignore this field (as it will be the same for all call-backs) but its inclusion allows other clients to make a single subscription call and then filter the responses.

**Comment by irajs** [comment]
Added to text.
