### ISSUE TITLE
timing CMAF and different adaptation sets

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#30]
1. If various Adaptation Sets carry the same events with different PTO, different presentation times need be used in the events,  would it make sense to discourage this practice  ? 
2. for CMAF PeriodStart = earliest presentation time  
     a) what if this time it not known (e.g. in live), 
          a1) recommend use of epoch/UTC ? 
          a2) would it make sense to recommend presentation_time_delta/version 0 
          in such cases tying to media time ?

**Comment by irajs** [comment]
For 1, the following text is already included in the document:

Note: If various Adaptation Sets carry the same events, different Adaptation Sets/Representations with different PTOs, the [=presentation_time_delta=] and/or [=presentation_time=] values might be different per Adaptation Set/Representation, i.e. the same emsg box can not be replicated over multiple Representations and/or Adaptations Sets.

For 2:
In the case of separate encoder and packager, i.e encoder provides a running live CMAF feed, but the packager start publishing MPD afterwards, either a1 or a2 needs to be used in encoder. Any preference is given in ingest spec?

**Comment by RufaelDev** [comment]
For 1: 
     my main question was, would it make sense to discourage such practices of same event with different    presentation time
For 2: 
     option a2 would probably be preferential as it explicitly ties to the media 
     timeline. Option a1 may not work too well for multiperiod content for example, as the period start time for second period may not be the UTC epoch

**Comment by haudiobe** [comment]
(Event TF 2019/06/14) Needs discussion for v5 - assigned label and milestone

**Comment by irajs** [comment]
For 1, I added a sentence to the note: 

Note: If various Adaptation Sets carry the same events, different Adaptation Sets/Representations with different PTOs, the [=presentation_time_delta=] and/or [=presentation_time=] values might be different per Adaptation Set/Representation, i.e. the same emsg box can not be replicated over multiple Representations and/or Adaptations Sets. Therefore, the use of same PTOs cross Adaptation Sets/Representations which carry the same events is encouraged.

For 2, also added a sentence in the corresponding note.
Note: In the case of [=CMAF=], PeriodStart is the CMAF track's earliest presentation time. If during the segment creation, this time is not known, it is recommeded to use the [=presentation_time_delta=].

**Comment by irajs** [comment]
(Event TF 6/28) The text currently adequately discussed the issue. A issue is already added in IOP V5.
