### ISSUE TITLE
@presentationTimeOffset

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#32]
@presentationTimeOffset states that events will be alligned to the period start and the presentationTimeoffset, however, the text in presentationTime contradicts this. For consistency the text in presentationTime should be updated

**Comment by haudiobe** [comment]
(Event TF 2019/06/14): needs update in our Event processing model and possibly in MPEG.

**Comment by irajs** [comment]
where exactly in the text?

**Comment by RufaelDev** [comment]
Figure 5 / Table 2

**Comment by irajs** [comment]
(Event TF 6/28) MPEG spec needs to be update. We will check what needed to be updated in MPEG spec and provide it to Goternburg meeting.

**Comment by haudiobe** [comment]
(Event TF 7/26)  added to MPEG-DASH 4th edition editing
