### ISSUE TITLE
inband event version 1

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#33]
presentationTime of inband event can be interpreted in two ways 

offset from period start (DASH)
offset from earliest presentation time (if CMAF is used)

while in the right direction, it is ambiguous, what if both DASH and CMAF are used ? what if the earliest presentation time is not known  (in case of live) ? 

It would be good to be even more explicit

**Comment by haudiobe** [comment]
(Event TF 2019/06/14): Time stamp is interpreted related to the presentation Time. Should be added in the current document of the client processing.

**Comment by irajs** [comment]
The anchor in DASH presentation is the Period Start, regardless of the source of content. If CMAF is used in DASH presentation and event are inserted during authoring of CMAF content,  the DASH period start shall be set to CMAF's EPT.  The following note in text already describes this:

Note: In the case of [=CMAF=], PeriodStart is the CMAF track's earliest presentation time. If during the segment creation, this time is not known, it is recommeded to use the [=presentation_time_delta=].

**Comment by RufaelDev** [comment]
looks ok to me!
