### ISSUE TITLE
Timed Metadata Track

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Events#43]
Submitter: Nicolas Weil
Email: nicoweil@elemental.com
Can we please add a MPD example in the document? It would be interesting to have a clear visibility on the DASH manifest signaling for TImed metadata tracks (including track mime-type and other fine grain details like that). Thanks.

**Comment by haudiobe** [comment]
(Event TF 7/26)  We need to start work on the content authoring (MPD, Segments, etc.) for Events and Timed Metadata. Needs to be in addition to APIs. New project. Please bring contributions

**Comment by RufaelDev** [comment]
i provide a sample mpd, to be reviewed on dashif reflector

**Comment by haudiobe** [comment]
(Event TF - 19/10/04) Need implementation guidelines on Events - deferred to version 2.

**Comment by RufaelDev** [comment]
Added contribution to implementation guidelines on this https://members.dashif.org/wg/Event/document/4464
