### ISSUE TITLE
Comments on Clause 2.2

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Events#47]
https://dashif-documents.azurewebsites.net/Events/master/event.html#emsg-format

Table 1 shows the DASHEventMessageBox emsg box format defined in MPEG DASH:

_A correct reference to MPEG-DASH is necessary_

The ST of an event can be calculated using values in its emsg box:

_What is ST? The presentation time of the event? It should be clarified what we want to calculate? The presentation time relative to the start of the Period? For the following this is asssumed_

_For version 0, the equation is wrong. It needs to say: (EPTmedia-PTOmedia)/timescalemedia + presentation_time_delta/timescalev0._

_For version 1, the equation is wrong. It needs to say: (presentation_time - PTOevent)/timescalev1._

Therefore, the use of same PTOs cross Adaptation Sets/Representations which carry the same events is encouraged.

_This is not good and misleading. This would mean that the event carriage defines the media format. This note should go away._

Note: In the case of CMAF, PeriodStart is the CMAF track’s earliest presentation time. If during the segment creation, this time is not known, it is recommeded to use the presentation_time_delta.

_This note is wrong as well. Please remove._

presentationtime = ST

_It needs to be clarified that the presentationtime is relative to the start of the Period._

**Comment by irajs** [comment]
The event emsg has its own time scale, different than media timescale carrying that event. Therefore, the calculation of event start time, the equations are taking account of applying those two timescales.

In the case of inserting the same events cross representations/adaptation sets, if the media timescale is different in those rep/adaptation sets, then the event emsg timing values needs to be adjusted to provide same event start time for all of them. 

In the case of CMAF, there is no period. When a CMAF presentation is delivered using DASH, the period is introduced. During the CMAF track creation, since there is no period yet, there is no anchor for emsg presentation time. Therefore, we have put this not that CMAF EPT should be used as anchor.

**Comment by haudiobe** [comment]
https://dashif-documents.azurewebsites.net/Events/master/event.html#emsg-format

Table 1 shows the DASHEventMessageBox emsg box format defined in MPEG DASH:

_A correct reference to MPEG-DASH is necessary_

*Accepted - implementation necessary*

The ST of an event can be calculated using values in its emsg box:

_What is ST? The presentation time of the event? It should be clarified what we want to calculate? The presentation time relative to the start of the Period? For the following this is asssumed_

*ST is the presentation time of the Event*

_For version 0, the equation is wrong. It needs to say: (EPTmedia-PTOmedia)/timescalemedia + presentation_time_delta/timescalev0._

*Correct, needs to be updated. Check the definition of AT. timescale also is embedded.*

_For version 1, the equation is wrong. It needs to say: (presentation_time - PTOevent)/timescalev1._

*Correct, needs to be updated. Side NOTE: Also check the PTOevent in CMAF. Aligned with what you do with tracks.*

Therefore, the use of same PTOs cross Adaptation Sets/Representations which carry the same events is encouraged.

_This is not good and misleading. This would mean that the event carriage defines the media format. This note should go away or be checked in detail. Please clarify._

*Leave out for client processing, rediscuss in authoring*

Note: In the case of CMAF, PeriodStart is the CMAF track’s earliest presentation time. If during the segment creation, this time is not known, it is recommeded to use the presentation_time_delta.

_This note is wrong as well. Please remove._

*Leave out for client processing, rediscuss in authoring. Also needs to be rediscussed in CMAF.*

presentationtime = ST

_It needs to be clarified that the presentationtime is relative to the start of the Period._

*Agreed, please implement.*
