### ISSUE TITLE
Timing Naming Consistency

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#5]
Timing is key aspect of Events. Right now different naming are used e.g. in DASH event timing model,
it would be good to have consistent naming as this naming will propagate to other specs such as the ingest spec. 

inband:
EST -> event start time
EPT -> earliest presentation time

metatrack: 
SET  -> earliest sample time (sample time of earliest sample fragment) 
MPT -> metadata sample presentation time

MPD Event:
PST -> period start time 
EST -> event start time

ingest spec correspondence: 
arrival/advertisement time -> EST/SET/PST 
application/presentation time -> EST/MPT/EST 

In each of the models there is a time the event is "announced" and a time the event 
is "executed" or "applied" it would be good to have consistent naming for this.

**Comment by irajs** [comment]
unified the names to common one:
RT (Received Time): earliest presentation time of segment or period
PT (Presentation Time): event/metadata sample start/presentation time
DU (Duration): event/sample duration

**Comment by RufaelDev** [comment]
Can we add the fact that this relates to events ? 
e.g. ERT (Event received time), EPT EDU etc, this will make it easier referring to events in other specifications like the ingest protocol

**Comment by irajs** [comment]
We can, but I intentionally removed the word "event" as we discussed to have  single set of terms for both events and timed metadata. If we put back event, e.g ERT/EPT/EDU, won't be confusing regarding their applicability to timed metadata?
