### ISSUE TITLE
Register interest in an event in Browser

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Events#51]
Submitter: Rik Sagar
Email: rik.sagar@vudu.com
Generally browser objects use addEventListener/removeEventListener to register interest in an event.  The setEvents([]) API seems inconsistent with that normal behavior. 

The proposed API also seems to be missing any method to remove existing listeners.

**Comment by haudiobe** [comment]
(Event TF - 19/10/04) Giri checks

**Comment by gmandyam** [comment]
EventTarget does support these methods:  https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener.  Note that EventTarget seems to have been deprecated in later versions of WebIDL:  https://www.w3.org/TR/WebIDL-1/.
