### ISSUE TITLE
Comments on clause 4.1.1

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Events#55]
4.1.1. Prerequisite

_this clause is not expected to have shalls, it only documents on what has happened_

Application subscribes to specific event stream as described in § 5 Prose description of APIs.

_Please make the subscribe event a separate section in clause 5 to be clearly refererenced. The above sentence should be changed to. "Application is subscribed to a specific event stream identified by a (scheme/value) pair with a specific dispatch_mode, either on start or on_receive."_

The processing model varies depending on dispatch_mode.

_This one can stay_

DASH Player shall follow the processing model outlined in this section.

_This sentence can be removed, unclear what it means._

DASH Player shall set up an Active Event Table for each subscribed scheme_uri/(value) in the case of dispatch_mode = on_start. Active Event Table maintains a single list of emsg’s id that have been dispatched.

_This sentence, if technically relevant, needs to be moved to the on_start mode_
_On the technical discussion: this speaks about emsg id, but the Event table is independent of emsg, it also holds for MPD events. The Active Event table maintains "objects" of Events._

**Comment by haudiobe** [comment]
(Event TF 2019/09/20) Agree to add it

**Comment by irajs** [comment]
4.1.1. Prerequisite

this clause is not expected to have shalls, it only documents on what has happened

_implemented_

Application subscribes to specific event stream as described in § 5 Prose description of APIs.



Please make the subscribe event a separate section in clause 5 to be clearly refererenced. 

_done._

The above sentence should be changed to. "Application is subscribed to a specific event stream identified by a (scheme/value) pair with a specific dispatch_mode, either on start or on_receive."

_done_

The processing model varies depending on dispatch_mode.

This one can stay

DASH Player shall follow the processing model outlined in this section.

This sentence can be removed, unclear what it means.

DASH Player shall set up an Active Event Table for each subscribed scheme_uri/(value) in the case of dispatch_mode = on_start. Active Event Table maintains a single list of emsg’s id that have been dispatched.

This sentence, if technically relevant, needs to be moved to the on_start mode
On the technical discussion: this speaks about emsg id, but the Event table is independent of emsg, it also holds for MPD events. The Active Event table maintains "objects" of Events.

_Implemented_

**Comment by haudiobe** [comment]
(Event TF - 19/10/04) Check implementation, if no further comments, will closed at next Event TF.
