### ISSUE TITLE
Comments on clause 1

### ISSUE THREAD

**Issue by inchoel** [Dash-Industry-Forum/Events#62]
https://dashif-documents.azurewebsites.net/Events/master/event.html#event-architecture
In Figure 1,  there's a minor typo. ('Dispacher' -> 'Dispatcher')

Please let me know what is transferred 
- from 'Media Buffer' to 'Event & T.Metadata Buffer'.
- from 'Synchronizer&Dispatcher' to 'Media Decoder'. (time information ?)

Thank you.

**Comment by irajs** [comment]
thanks for the comment.

typo was addressed in the new version in word document.

Added a note regarding the synchronization between Media buffer and metadata buffer:

Note: The metadata buffer maintains a sequence of events and timed metadata samples. The maintain and purging management of this buffer is synchronized with the Media buffer management.
