### ISSUE TITLE
Correct timing of events equations

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#63]
ST is supposed to be relative to start of period (according to section 3.1) 

if this is the case:

Equation 1 version 1 first term should be negative 

Equation 2 first term should be negative 

Section on timed metadata tracks: 
for metadata tracks you may also need to mention that, as metadata tracks are like media tracks
a presentationTime offset signalled in the adaptation set may need to be subtracted  

overal for timed metadata tracks an optional negative presentationTime offset is needed for consistency:

ST (respective to period start) = media presentation time / timescale  - (optional presentationTimeOffset)

This update would make ST relative to period start and consistent for each method

**Comment by RufaelDev** [comment]
https://github.com/Dash-Industry-Forum/Events/pull/64 
see the equations

**Comment by irajs** [comment]
It was implemented in the word version:

https://members.dashif.org/wg/Event/document/4445

 We don't maintain the markdown version anymore.

**Comment by irajs** [comment]
Updated the equation based on the clarification in MPEG #130 in Word document version 1.0.2.
