### ISSUE TITLE
event starting in past

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Events#68]
Events cannot be signalled in the past, this would mean some of the implications of inserting events again 
are not feasible at the moment. Note this is implication since DASH 4th edition. see:

https://github.com/Dash-Industry-Forum/Ingest/issues/132

consider if we want MPEG to fix this.

**Comment by irajs** [comment]
The MPEG spec restrictions were removed. So the presentation_time can be in past. However, if the client receive an event that started in past and ended in past, it may not process it.
