### ISSUE TITLE
Is it allowed to remove an EventStream from a Period with a manifest update?

### ISSUE THREAD

**Issue by ojw28** [Dash-Industry-Forum/Events#69]
This question came up in https://github.com/google/ExoPlayer/pull/9196.

I can't find anything in the DASH spec or the DASH-IF guidelines indicating whether this is allowed. I would suspect (and would pitch) that `EventStream` elements should not be added or removed across MPD updates, but should instead be present but empty if the current live window does not contain any events. Else the presence of events in the period is not being correctly signalled at all times during playback.

Thoughts?

**Comment by RufaelDev** [comment]
I think as there was no such restriction before, EventStreams can indeed be removed from the manifest. I don't see why an EventStream cannot be removed from the manifest in case it is no longer used.

**Comment by jpiesing** [comment]
> I think as there was no such restriction before, EventStreams can indeed be removed from the manifest. I don't see why an EventStream cannot be removed from the manifest in case it is no longer used.

If the general rule is not removing things as @haudiobe  proposed, making an exception for EventStreams would make me nervous. Exceptions need to be explicitly documented and tested.

**Comment by RufaelDev** [comment]
My point is that there is content out there that is 100 percent valid and we want to make sure that is not invalidated, further players need to deal with such content as it is beinging used. Practically speaking, event and eventstreams move out the DVR window and dissapear, so such occurences can actually quite likely in true live streams.

**Comment by jpiesing** [comment]
> My point is that there is content out there that is 100 percent valid and we want to make sure that is not invalidated, 

The exact same thing can be said about players too. Unfortunately once the spec is unclear & silent about certain things and they're not tested then some will interpret that as "anything not explicitly prohibited is allowed" and others will interpret it as "anything not explicitly allowed (or tested) is not valid".
Sometimes, unfortunately, it is impossible to resolve a specification ambiguity without invalidating something.

**Comment by irajs** [comment]
Removal of the Eventstream or adding them is allowed.

The author of the event must assure that removal of the EventStream does not impact the playback for the client which join later and do not see the EventStream, i.e. the client seeing it and not seeing it behave correctly.


We make sure that the guidelines mentions the addition and removal of EventStream element.

**Comment by jpiesing** [comment]
> Removal of the Eventstream or adding them is allowed.
> 
> The author of the event must assure that removal of the EventStream does not impact the playback for the client which join later and do not see the EventStream, i.e. the client seeing it and not seeing it behave correctly.
> 

I was more concerned about clients that had seen the EventStream being robust when it vanishes on an MPD update.


> We make sure that the guidelines mentions the addition and removal of EventStream element.

**Comment by irajs** [comment]
[Event TF call 7/8/2022] Added a sentence in 7.2.5.
