### ISSUE TITLE
Comments on IOP v5 Part 10 review

### ISSUE THREAD

**Issue by pmaness** [Dash-Industry-Forum/Events#70]
I think everything here is editorial. 

General suggestion: Referencing in the document body is somewhat inconsistent. Some are tagged as just the number e.g. [1], and some are not referred by number at all, only by the spec. name. The reference number should be indicated, for example https://dashif/.org/docs/DASH-IF-IOP-for-ATSC3-0-v1.1.pdf [i.4], or better yet, use a short handle for the spec names in the document body, for example SCTE [i.1], DVB [i.2], AOMedia [i.3] and ATSC [i.4] might make for improved readability. Could do the same for the normative references, e.g. DASH [1], ISOBMFF [2], CMAF [3] and Event Msg [4].

Additional comments are consecutive, by section number:

3.3 - 3 abbreviations don't seem to appear in the document: AEMS, DU and ST. If they aren,'t used, they should be removed.

Table 6-2 - values in Field_type column should be lower case. Depending on adopted convention, labels in the table heading could also be lower case

6.2.1 - I think the "a." and "b." numbering is not needed in the first part, separating them as paragraphs is clear. 

6.2.2.3 - should have a lead-in sentence before the numbered list

6.2.2.4 - numbering should be removed? (or add a lead-in)

6.2.5 - needs a lead-in sentence before the numbered list (like what 6.2.6 and 6.3 have)

7.2.4 needs lead-in sentence before the numbered list

7.2.9 terminate the lead-in sentence with a colon (instead of a period) before the numbered list

9.2.5 above the two examples, replace the word "below" with the respective labels (Example 9-1 and Example 9-2)

**Comment by irajs** [comment]
> General suggestion: Referencing in the document body is somewhat inconsistent. Some are tagged as just the number e.g. [1], and some are not referred by number at all, only by the spec. name. The reference number should be indicated, for example https://dashif/.org/docs/DASH-IF-IOP-for-ATSC3-0-v1.1.pdf [i.4], or better yet, use a short handle for the spec names in the document body, for example SCTE [i.1], DVB [i.2], AOMedia [i.3] and ATSC [i.4] might make for improved readability. Could do the same for the normative references, e.g. DASH [1], ISOBMFF [2], CMAF [3] and Event Msg [4].
> 
[i.x] added to tables and other references are using DASH[1] convention now.

> Additional comments are consecutive, by section number:
> 
> 3.3 - 3 abbreviations don't seem to appear in the document: AEMS, DU and ST. If they aren,'t used, they should be removed.
> 
> Table 6-2 - values in Field_type column should be lower case. Depending on adopted convention, labels in the table heading could also be lower case
> 
> 6.2.1 - I think the "a." and "b." numbering is not needed in the first part, separating them as paragraphs is clear.
> 
> 6.2.2.3 - should have a lead-in sentence before the numbered list
> 
> 6.2.2.4 - numbering should be removed? (or add a lead-in)
> 
> 6.2.5 - needs a lead-in sentence before the numbered list (like what 6.2.6 and 6.3 have)
> 
> 7.2.4 needs lead-in sentence before the numbered list
> 
> 7.2.9 terminate the lead-in sentence with a colon (instead of a period) before the numbered list

all fixed.

> 9.2.5 above the two examples, replace the word "below" with the respective labels (Example 9-1 and Example 9-2)

Referenced the actual example 9-1 and 9-2.


thanks for the careful review.
