### ISSUE TITLE
Need confirm perority between MPD events and Inband events.

### ISSUE THREAD

**Issue by AUGxhub** [Dash-Industry-Forum/Events#71]
as writes in following charpter 
8	Combination of MPD events and Inband events  

the question is : when same type event exsit in both cases ,which has higher perpority ? 
especially , same type different value (action) cases

**Comment by irajs** [comment]
There is no higher priority between MPD and inband event instances. Events regardless of their delivery mechanism (MPD or inband) are parsed when received and put in the event processing pipeline. If an equivalent event was already observed by the client, the newer events are not processed, regardless of being MPD or inband events.

[Event TF call  7/22] added a sentence to section 8.

**Comment by AUGxhub** [comment]
@irajs  , please mark the rule in final spec
