### ISSUE TITLE
unclear event should not be consider in spec tag:atsc.org,2016:event

### ISSUE THREAD

**Issue by AUGxhub** [Dash-Industry-Forum/Events#72]
unclear event should not be consider in spec 
for "tag:atsc.org,2016:event " , where is the detail defination of it ?

**Comment by irajs** [comment]
[Event TF 7/8] we wait for ATSC's response on this event. If we get more info, we add it to the spec otherwise remove it. Overall, the plan is to move the consortia-defined events to the dashif.org identifiers page.

**Comment by AUGxhub** [comment]
fine
