### ISSUE TITLE
A few editorial suggestions

### ISSUE THREAD

**Issue by chrisn** [Dash-Industry-Forum/Events#73]
Here are some very minor editorial issues I noticed when reading through the draft for community review: https://dashif.org/docs/DASH-IF-IOPv5.0-Part10-DRAFT-V0.95.pdf

### Document metadata

The document title shows as "SKELETON" when the PDF is viewed in the browser, suggest updating the document metadata

### Page 6: Introduction

Both Part 8 and Part 10 are labelled as "this document"

### Page 7: Scope

timed sensitive -> time sensitive

### Page 11: 6.2.1 Dispatch mode selection

the to -> to the

### Page 14: 7.2.4 Event timing considerations

before Period start time -> before the Period start time

### Page 14: 7.2.5 Announcement and removal of Events in the MPD

minimum in-advance offset insert -> minimum in-advance offset to insert (?)

### Page 16: 9.2.1 Dispatch mode selection

on at the -> at the

### Page 16: 9.2.5 MPD signaling

Exampl -> Example

Also, Example 9-1 uses a mixture of straight and curly quotes

### Page 17: 9.2.6 Metadata samples carrying the same event instances

Exampl -> Example

Also, Example 9-2 uses a mixture of straight and curly quotes

### Page 18: Support of DASH events

In Table 10-1: "Refenrece" -> "Reference"

### Page 18: 11.1 SCTE 214

urn: scte:scte35:2013:bin -> urn:scte:scte35:2013:bin

### Page 19: 11.4 HbbTV

an scheme -> a scheme

I also noted that the draft says "map the DASH event to HTML DataCue’s TextTrack". DataCue isn't defined in the current WHATWG HTML specification, instead in W3C HTML5. There is currently no standard DataCue API that has support across multiple browser engines.

### Page 19: 11.5 ATSC 3.0

dispatch model -> dispatch mode

**Comment by chrisn** [comment]
Another issue I just found:

### 9.2.6 Metadata samples carrying the same event instances

The second paragraph says: "... carry additional ids to detect duplicated ISO/IEC 23001-18 spanning multiple samples". Should this be something like: "... carry additional ids to detect duplicates spanning multiple samples"?

**Comment by irajs** [comment]
[Event TF] addressed all comments but the first one (pdf).
