### ISSUE TITLE
Part 10- Section 11.1- SCTE 214 change to  Explicit Dispatch Mode

### ISSUE THREAD

**Issue by Yasser-Comcast** [Dash-Industry-Forum/Events#74]
There is a new revision of 214-1 ((https://www.scte.org/documents/5147/ANSI_SCTE_214-1_2022.pdf) that does explicitlyh state that the on -receive mode should be used. 
"SCTE 35 DASH Events shall operate in an “on-receive” dispatch mode. Events will be dispatched at or before the event time to the Application [as defined in DASH 5th edition and DASH-IF 5.0]."

**Comment by irajs** [comment]
Event TF call 8/5:

Thank you for adding it to the new version. The community review was changed to reflect this.
