### ISSUE TITLE
Repeat events

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/Events#8]
The current spec says:
```

In the case of event: Compare the event's id with the entries of [=Active Event Table=] of the same scheme_uri/(value pair:

    If an entry with the identical id value exists, end processing;
    If not, add emsg’s id to the corresponding [=Active Event Table=].
```

This means that the event payload is always dropped unless this is the first time an event with a given ID is encountered. However, the repeat event may have different information (payload, time, duration) and may have been intended to override the initial event with the same ID.

**Comment by haudiobe** [comment]
Yes, this is the correct behaviour for the synchronized events - simplicity wins. If you want the feature, create your application logic based on the payload.

If you want to it for non-synchronized API, you can hand repeated events. In the latter case you can do what you want. But then you need to do sync as well.

**Comment by ZmGorynych** [comment]
If you want consistent behavior irrespective of the first segment the client is seeing (i.e., the tune-in point), you need to process the latest, and not the earliest, version of the event.
Simplicity has nothing to do with this -- it is deterministic behavior of the client.

**Comment by irajs** [comment]
the required behavior for the client is for the first event it sees. So in the case of tune-in, the first event after tune in (and not the first event in stream) is seen by client and is required processed. If a new event is sent that has different effect (so instance undo the first event) then it is considered a separate event and should not have same id.

**Comment by ZmGorynych** [comment]
In many cases SCTE 35 for the same ad break is sent multiple times, as a
countdown.

**Comment by irajs** [comment]
if the application should see the count down, then they are not identical message, because there is a difference between message i and message i+1, so they should not have same @id.

**Comment by ZmGorynych** [comment]
Do we say that payloads have to be bit-identical for same id?

**Comment by irajs** [comment]
no. should be equivalent i.e  process either one has same effect

Sent from mobile. Please excuse the briefness &Typos.

Iraj Sodagar
On May 10, 2019, at 5:59 PM, Alex Giladi <notifications@github.com<mailto:notifications@github.com>> wrote:
Do we say that payloads have to be bit-identical for same id?

**Comment by irajs** [comment]
no. we say they should have same effect, processing one is like processing the other.

**Comment by ZmGorynych** [comment]
I'm a bit concerned we're leaving room for non-deterministic behavior triggered by linear channel constraints (i.e., you don't control your event input as they are inserted upstream). Having a "last one" instead of "first one" policy costs nothing complexity-wise, but avoids non-deterministic behavior.

**Comment by irajs** [comment]
I agree that in terms of processing it would cost the same to process any equivalent events. However, my question is: how does the client know this is the last one? or how does it know this event will be repeated and it doesn't need to process it right away?

**Comment by irajs** [comment]
Can we close this issue?

**Comment by haudiobe** [comment]
(Event TF 2019/06/14) Close w/o action if no further comment
