### ISSUE TITLE
Event cancelation

### ISSUE THREAD

**Issue by ZmGorynych** [Dash-Industry-Forum/Events#9]
The text does not allow for cancellation of an on-start event. We can probably achieve this by means such as reserving duration of zero in a repeat event to cancelation of prior event with same id

**Comment by haudiobe** [comment]
No, we should not do any of this. It is all application logic to cancel an event. We have nothing like this in the File Format either, so why would we need that logic. DASH does not support this today and it cannot be solved in the processing model.

**Comment by irajs** [comment]
In the case of "on_receive" the application has to take care of canceling anyway, as the first event has  been already passed to the application at the time the cancel event is received. 

In the case of "on_start" mode, a cancel event can avoid dispatching an event that its start time has not reached yet. But 1) it need explicit signalling 2) All event's information should have been in payload (beside scheme id and value) in the first place and left to scheme define its parameters. Adding more just adds logic to DASH client. App can received the cancel event before the event itself, and when it receive it, it ignore it.

**Comment by irajs** [comment]
can we close this issue?

**Comment by haudiobe** [comment]
(Event TF 2019/06/14) Close w/o action if no further comment
